language: php

php:
  - 7.1
  - 7.2
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - pecl install -f ast

install:
  - rm -f composer.lock  # temporary fix for PHPUnit 8
  - composer install --prefer-dist --no-progress

script:
  - composer analyze
  - composer test
