language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - pecl install -f ast

install:
  - composer install --prefer-dist --no-progress --ignore-platform-reqs

script:
  - composer analyze
  - composer test
